<?php

include($_SERVER["DOCUMENT_ROOT"] . "/wp-config.php");
$link = mysql_connect(DB_HOST,DB_USER,DB_PASSWORD);

// To shield your database from SQL injection requests, protect $_REQUEST parameters with mysql_real_escape_string
// Read more: http://www.yourhelpcenter.de/2009/06/mysql-schutz-vor-angriffen-in-datenbankabfragen-sql-injection/
foreach ($_REQUEST as $key => $val)
	$_REQUEST["$key"] = mysql_real_escape_string($val);

// Check, if IPLA API is enabled
$sql = "select option_value from " . $table_prefix . "options where option_name='ip_logger_ipla_enabled'";
$res = mysql_query($sql);
$row = mysql_fetch_assoc($res);

// Save this IPLA communication (timestamp and IP)
$sql = "update " . $table_prefix . "options " .
	   "set option_value = CURRENT_TIMESTAMP " .
	   "where option_name='ip_logger_ipla_LastContact_Stamp'";
$res = mysql_query($sql);

$sql = "update " . $table_prefix . "options " .
	   "set option_value = '" . $_SERVER["REMOTE_ADDR"] . "' " .
	   "where option_name='ip_logger_ipla_LastContact_IP'";
$res = mysql_query($sql);

//
if ($row["option_value"] != "1")
	exit();

// PIN prüfen
$sql = "select option_value from " . $table_prefix . "options where option_name='ip_logger_ipla_PIN'";
$res = mysql_query($sql);
$row = mysql_fetch_assoc($res);
$pin = $row["option_value"];

if ($pin != $_REQUEST["PIN"]) {
	exit();
}

function xmlHeader($total) {

	// Writes the default XML header
	echo "<?xml version=\"1.0\"?>\n"; 
	// "<?xml version='1.0' encoding='UTF-8' standalone='yes' ? >\n";
	echo "<!-- Generated by IP Logger Manager: ".date("d.m.Y H:i:s")." -->\n";
	echo "<!-- (c) Copyright 2009,2010 by M. Retzlaff (info@mretzlaff.com) -->\n";
	echo "<!-- Homepage: http://www.mretzlaff.com/ip-logger-analyzer/ -->\n";
	echo "<IPLoggerAnalyzer>\n";
	echo "<Request>\n";
	foreach ($_REQUEST as $key => $value) {
		echo "<$key>".($key == "PIN" ? "***" : $value)."</$key>\n";
	}
	echo "</Request>\n";
	echo "<Result>\n";
	echo "<Records>$total</Records>\n";
	echo "</Result>\n";
}

function encode($key, $value) {
	if ($key == "http_referer" || 
	    $key == "url" ||
	    $key == "City" ||
	    $key == "user_agent")
		return urlencode($value);
	else
		return $value;
}

if ($_REQUEST["type"] == "getGUID") {

	$sql = "select option_value from " . $table_prefix . "options where option_name='ip_logger_ipla_GUID'";
	$res = mysql_query($sql);
	$row = mysql_fetch_assoc($res);
	$pin = $row["option_value"];
	
	echo $pin;
}

if ($_REQUEST["type"] == "getData") {

	if ($_REQUEST["question"] == "DaysWithHits") {

		// Find all date with hits before today
		// Info: The current hits (those from today) are not downloadable because not statistics (on the webserver)
		// has been created so far. Due to that, those hits could get lost in that statistics.
		$sql = 	"SELECT distinct DATE_FORMAT(stamp,'%Y-%m-%d') as stamp " .
			   	"FROM " . $table_prefix . "ip_logger_hits " .
			   	"WHERE date(stamp) <= DATE_ADD(CURDATE(), INTERVAL -1 DAY) ".
			   	(!empty($_REQUEST["startDate"]) ? sprintf("AND date(stamp) > '%s' ", $_REQUEST["startDate"]) : "") .
			   	"ORDER BY 1 asc";
		$res = mysql_query($sql);
		xmlHeader(mysql_num_rows($res));

		// Print each date as a single node
		echo "<Records>\n";
		while ($row = mysql_fetch_assoc($res)) {
			echo "<Date>" .$row["stamp"] . "</Date>\n";
		}
		mysql_free_result($res);
		echo "</Records>\n";
		
		// Print the sum of hits for those days
		$sql = 	"select count(id) as total from " . $table_prefix . "ip_logger_hits " .
				"WHERE date(stamp) <= DATE_ADD(CURDATE(), INTERVAL -1 DAY) " .
			   	(!empty($_REQUEST["startDate"]) ? sprintf("AND date(stamp) > '%s'", $_REQUEST["startDate"]) : "");
	
		$res = mysql_query($sql);
		$row = mysql_fetch_assoc($res);
		echo "<TotalHits>\n";
		echo "<Total>" . $row["total"] . "</Total>\n";
		echo "</TotalHits>\n";
		mysql_free_result($res);
		
		// Close the XML tag
		echo "</IPLoggerAnalyzer>";
	}

	// http://mretzlaff.com/wp-content/plugins/ip-logger/manager.php?type=getData&question=HitsOfSingleDate&Date=2010-01-17
	if ($_REQUEST["question"] == "HitsOfSingleDate" && !empty($_REQUEST["Date"])) {

		$sql = "select * from " . $table_prefix . "ip_logger_hits where DATE_FORMAT(stamp,'%Y-%m-%d') = '".$_REQUEST["Date"]."' order by id asc";
		$res = mysql_query($sql);

		xmlHeader(mysql_num_rows($res));
		echo "<Records>\n";
		while ($row = mysql_fetch_assoc($res)) {
			echo "<Hit>\n";
			foreach ($row as $key => $value) {
				echo sprintf("<%s>%s%s%s</%s>\n", 
					$key,
					"", //($key == "http_referer" ? "<![CDATA[" : ""),
					encode($key, $value),
					"", //($key == "http_referer" ? "]]>" : ""),
					$key);
			}
			echo "</Hit>\n";
		}
		mysql_free_result($res);
		echo "</Records>\n";
		echo "</IPLoggerAnalyzer>";
	}
}

if ($_REQUEST["type"] == "delData") {
	
	if ($_REQUEST["command"] == "DeleteSingleDate" && strlen($_REQUEST["Date"]) == 10) {
	
		// *** ip_logger_totalcounter_hits_saved ***
		// How many hits were recorded that day ?
		$sql = "select count(*) as anzahl from " . $table_prefix . "ip_logger_hits where DATE_FORMAT(stamp,'%Y-%m-%d') = '".$_REQUEST["Date"]."'";
		$res = mysql_query($sql);
		$row = mysql_fetch_assoc($res);
		$hits = $row["anzahl"];
	
		// How many hits will be deleted ?
		$sql = "select option_value from " . $table_prefix . "options where option_name = 'ip_logger_totalcounter_hits_saved'";
		$res = mysql_query($sql);
		$row = mysql_fetch_assoc($res);
		$done = $row["option_value"];
		
		// Update the internal counter
		$sql = "update " . $table_prefix . "options set option_value = ".($done+$hits)." where option_name = 'ip_logger_totalcounter_hits_saved'";
		$res = mysql_query($sql);
			
		// *** ip_logger_totalcounter_hits_blocked ***
		// How many hits were recorded that day ?
		$sql = "select count(*) as anzahl from " . $table_prefix . "ip_logger_hits " .
			   "where DATE_FORMAT(stamp,'%Y-%m-%d') = '".$_REQUEST["Date"]."' AND blocked = 'Y'";
		$res = mysql_query($sql);
		$row = mysql_fetch_assoc($res);
		$hits = $row["anzahl"];
	
		// How many hits will be deleted ?
		$sql = "select option_value from " . $table_prefix . "options where option_name = 'ip_logger_totalcounter_hits_blocked'";
		$res = mysql_query($sql);
		$row = mysql_fetch_assoc($res);
		$done = $row["option_value"];
		
		// Update the internal counter
		$sql = "update " . $table_prefix . "options set option_value = ".($done+$hits)." where option_name = 'ip_logger_totalcounter_hits_blocked'";
		$res = mysql_query($sql);
		
		// *** ip_logger_totalcounter_hits_ignored ***
		// How many hits were recorded that day ?
		$sql = "select count(*) as anzahl from " . $table_prefix . "ip_logger_hits " .
			   "where DATE_FORMAT(stamp,'%Y-%m-%d') = '".$_REQUEST["Date"]."' AND ignored = 'Y'";
		$res = mysql_query($sql);
		$row = mysql_fetch_assoc($res);
		$hits = $row["anzahl"];
	
		// How many hits will be deleted ?
		$sql = "select option_value from " . $table_prefix . "options where option_name = 'ip_logger_totalcounter_hits_ignored'";
		$res = mysql_query($sql);
		$row = mysql_fetch_assoc($res);
		$done = $row["option_value"];
		
		// Update the internal counter
		$sql = "update " . $table_prefix . "options set option_value = ".($done+$hits)." where option_name = 'ip_logger_totalcounter_hits_ignored'";
		$res = mysql_query($sql);
		
		// *******************************************	
		// Delete the hits for the day
		$sql = "delete from " . $table_prefix . "ip_logger_hits where DATE_FORMAT(stamp,'%Y-%m-%d') = '".$_REQUEST["Date"]."'";
		$res = mysql_query($sql);
		// echo mysql_affected_rows();
		//mysql_free_result($res);
	}
}

mysql_close($link);
?>